# Generated by Django 5.0.2 on 2025-05-29 09:53

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('creation_time', models.DateTimeField(default=datetime.datetime.utcnow)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
